print("Welcome to this mad lib project. Let's begin!")
#print("A Conversation Between Teacher and Student\n")
#print("Student: You called me?\nTeacher: I did. I want to discuss your ~noun~. ")
blank1=input("Enter noun: ")
#print("Student: Not that again. What is it ~adverb~?")
blank2=input("Enter adverb: ")
#print("Teacher: Don't give me that ~noun~. You're ~verb~ing")
blank3=input("Enter noun: ")
blank4=input("Enter verb: ")
#print("Student: Oh..What can I do to ~verb~ my scores?")
blank5=input("Enter verb: ")
#print("Teacher: You will have to ~verb~ some ~plural noun~.")
blank6=input("Enter verb: ")
blank7=input("Enter plural noun: ")
#print("Student: That will be ~adjective~.\nTeacher: I hope so. If this gets ~adjective~, I'll have to ~verb~ your ~noun~.")
blank8=input("Enter adjective: ")
blank9=input("Enter adjective: ")
blank10=input("Enter verb: ")
blank11=input("Enter noun: ")
#print("Student: Alright alright I get it. I'll ~verb~ to ~noun~ tomorrow then.")
blank12=input("Enter verb: ")
blank13=input("Enter noun: ")
#print("Teacher: No, not tomorrow. I have to ~verb~ over some of ~name~'s ~plural noun~.")
blank14=input("Enter verb: ")
blank15=input("Enter a name: ")
blank16=input("Enter plural noun: ")
#print("Student: Yeah yeah. Then how about ~time~?")
blank17=input("Enter a time: ")
#print("Teacher: That will do. See you then.")
print("\nA Conversation Between Teacher and Student")
print("Student: You called me?")
print("Teacher: I did. I want to discuss your "+blank1+".")
print("Student: Not that again. What is it "+blank2+"?")
print("Teacher: Don't give me that "+blank3+".You're "+blank4+"ing.")
print("Student: Oh..What can I do to "+blank5+" my scores?")
print("Teacher: You will have to "+blank6+" some "+blank7+".")
print("Student: That will be "+blank8+".")
print("Teacher: I hope so. If this gets "+blank9+", I'll have to "+blank10+" your "+blank11+".")
print("Student: Alright alright I get it. I'll "+blank12+" to "+blank13+" tomorrow then.")
print("Teacher: No, not tomorrow. I have to "+blank14+" over some of "+blank15+"'s "+blank16+".")
print("Student: Yeah yeah. Then how about "+blank17+"?")
print("Teacher: That will do. See you then.")
